version: '3.0'
services:
  es1:
    container_name: elasticsearch
    build: docker/elasticsearch/
    volumes:
      - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - procc_network

#  kibana:
#    build: docker/kibana/
#    volumes:
#      - ./docker/kibana/config/:/usr/share/kibana/config:ro
#    ports:
#      - '5601:5601'
#    depends_on:
#      - es1
#    networks:
#      - procc_network

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'
    networks:
      - procc_network
  api:
    container_name: storefront_api
    build:
      context: .
      dockerfile: ./docker/vue-storefront-api/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - '8080:8080'
    command: "/bin/sh"
    stdin_open: true
    tty: true
    depends_on:
      - es1
      - redis
    networks:
      - procc_network

# networks:
#   procc_network:
#     driver: bridge

networks:
  procc_network:
    external: true

volumes:
  esdat1:
