version: '3.0'
services:
  es7:
    container_name: elasticsearch7
    build: docker/elasticsearch7/
    volumes:
      - ./docker/elasticsearch7/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - '9200:9200'
      - '9300:9300'

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'
