#!/bin/sh

docker logs storefront_api -f

echo " === VSF API -> Logs Started \n"
echo "docker storefront logs        ->   (VSF Vue)"
echo "docker storefront_api logs     ->   (VSF API)"
echo "docker procc logs             ->   (ProCC Vue)"
echo "docker procc logs             ->   (ProCC API)"
