#!/bin/sh

docker restart storefront_api

echo " === VSF API -> storefront_api Restarted \n"
echo "docker logs storefront -f       ->   (VSF Vue)"
echo "docker logs storefront_api -f   ->   (VSF API)"
echo "docker logs procc -f            ->   (ProCC Vue)"
echo "docker logs procc -f            ->   (ProCC API)"
