#!/bin/sh

docker restart storefront_api

echo " === VSF API -> storefront_api Restarted \n"
echo "docker storefront logs       ->   (VSF Vue)"
echo "docker storefront_api logs    ->   (VSF API)"
echo "docker procc logs            ->   (ProCC Vue)"
echo "docker procc logs            ->   (ProCC API)"
