#!/bin/sh

### Fixing issue with files created by the docker containers in root mode...
echo "   ---   Fixing issue with files created by the docker containers in root mode..."
echo "running sudo chmod -R 777 ."
sudo chmod -R 777 .

docker-compose -f docker-compose-dev.yml up -d

echo " === VSF API -> storefront_api Restarted \n"
echo "docker logs storefront -f       ->   (VSF Vue)"
echo "docker logs storefront_api -f   ->   (VSF API)"
echo "docker logs procc -f            ->   (ProCC Vue)"
echo "docker logs procc -f            ->   (ProCC API)"
