apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic5
  template:
    metadata:
      labels:
        app: elastic5
    spec:
      containers:
      - name: elastic5
        image: gcr.io/advance-anvil-247513/elastic5
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
          - name: ES_JAVA_OPTS
            value: "-Xmx512m -Xms512m"
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 512Mi
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data2
            name: nfs-drive
            subPath: es5_data
          - mountPath: /usr/share/elasticsearch/config2
            name: nfs-drive
            subPath: es5_config
      initContainers:
        - name: sysctl
          image: busybox:1.27.2
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      volumes:
        - name: nfs-drive
          persistentVolumeClaim:
            claimName: nfs-drive-pvc
