apiVersion: v1
kind: Service
metadata:
  name: elastic5
  labels:
    app: elastic5
spec:
  selector:
    app: elastic5
  ports:
  - port: 9200
    targetPort: 9200
    name: "9200"
  - port: 9300
    targetPort: 9300
    name: "9300"
