apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-storefront-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-storefront-api
  template:
    metadata:
      labels:
        app: vue-storefront-api
    spec:
      containers:
      - name: vue-storefront-api
        image: gcr.io/advance-anvil-247513/vue-storefront-api
        envFrom:
        - configMapRef:
            name: vue-storefront-api-config
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /var/www/dist
            name: build-cache
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 256Mi
      volumes:
        - name: build-cache
          emptyDir:
            medium: Memory
